#pragma once

#include "agk.h"

#include <vector>

#include "World.h"
#include "Tile.h"
#include "Waypoint.h"
#include "I.h"

class Player
{
public:
	Player(void);
	~Player(void);

	void begin(); //Function which acts as a constructor while the issues with them persist

	void Spawn();

	void update();
	void load();

	float getX();
	float getY();

	//Pointer to the world
	World* world;

	std::vector<Waypoint>* path;
private:
	//Media variables
	int joystick;
	int SID;

	//Position variables
	float x;
	float y;

	int tileX;
	int tileY;

	float angle;

	int spawnX;
	int spawnY;

	bool hasPath; //True if the player has a path to walk which is generated by the pathfinder
	int cWaypoint; //The current waypoint on the path

	float speed;
};
